### ISSUE TITLE
Error pulling image (latest) from mariadb, HTTP code 400

### ISSUE THREAD

**Issue by fadehelix** [FoodCoopSystem/docker#1]
When I run `docker-compose up` I get following error:

``` bash
docker-compose up
Creating foodcoop_db_1...
Pulling image mariadb:latest...
Pulling repository mariadb
d2eb470596a9: Error pulling image (latest) from mariadb, HTTP code 400
8ebbde154a62: Download complete
c12da83ee7c1: Download complete
a16207605ac6: Error pulling dependent layers
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 464, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 208, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 214, in recreate_containers
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 199, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 37, in stream_output
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 50, in print_output_event
compose.progress_stream.StreamOutputError: Error pulling image (latest) from mariadb, HTTP code 400

```

**Comment by jsobiecki** [comment]
Hmmm, from this error message, it looks like docker registry hub server returned HTTP error 400 (Bad request). It's strange. Could you please repeat, and check if it wasn't temporary? 

If problem still occurs, please execute docker-compose command with --verbose flag.

**Comment by fadehelix** [comment]
Here is output generated by `docker-compose --verbose up`

``` bash
Compose version 1.2.0
Docker base_url: http+unix://var/run/docker.sock
Docker version: KernelVersion=3.18.0-031800-generic, Arch=amd64, ApiVersion=1.15, Version=1.3.3, GitCommit=d344625, Os=linux, GoVersion=go1.3.3
docker containers <- (all=True)
docker containers -> (list with 10 items)
Creating foodcoop_db_1...
docker containers <- (all=True)
docker containers -> (list with 10 items)
docker create_container <- (name=u'foodcoop_db_1', image=u'mariadb:latest', host_config={'Binds': [], 'PortBindings': {'3306/tcp': [{'HostPort': '3306', 'HostIp': ''}]}, 'NetworkMode': u'bridge', 'Links': [], 'VolumesFrom': []}, environment={'MYSQL_ROOT_PASSWORD': 'root', 'MYSQL_DATABASE': 'foodcoop'}, detach=False, ports=[u'3306'])
Pulling image mariadb:latest...
docker pull <- (u'mariadb:latest', insecure_registry=False, stream=True)
docker pull -> <generator object _stream_helper at 0x209bdc0>
Pulling repository mariadb
d2eb470596a9: Error pulling image (latest) from mariadb, HTTP code 400
8ebbde154a62: Download complete
c12da83ee7c1: Download complete
a16207605ac6: Error pulling dependent layers
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 464, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 208, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 214, in recreate_containers
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 199, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 37, in stream_output
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 50, in print_output_event
compose.progress_stream.StreamOutputError: Error pulling image (latest) from mariadb, HTTP code 400

```

**Comment by jsobiecki** [comment]
Ok, and what happens, if you execute docker pull mariadb ?

**Comment by fadehelix** [comment]
``` bash
Pulling repository mariadb
d2eb470596a9: Error pulling image (latest) from mariadb, HTTP code 400 
8ebbde154a62: Download complete 
c12da83ee7c1: Download complete 
a16207605ac6: Error pulling dependent layers 
2015/06/14 09:00:40 Error pulling image (latest) from mariadb, HTTP code 400
```

**Comment by jsobiecki** [comment]
Ok, it's really problematic. Let's check few things
- What is your docker version 
-  Are you able to pull any image from registry? Try docker pull mongo

**Comment by fadehelix** [comment]
`docker pul mongo` works well, but when I tried `docker pull mysql` I saw the same error. 
My docker version:

``` bash
Client version: 1.3.3
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): d344625
OS/Arch (client): linux/amd64
Server version: 1.3.3
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): d344625
```

**Comment by fadehelix** [comment]
I've tried today and `docer-compose up` magically works :)
